server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:woloxgram-db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


feign:
  jsonplaceholder:
    url: https://jsonplaceholder.typicode.com/
    users: users
    users-albums: users/{userId}/albums
    users-photos: users/{userId}/photos
    photos: photos
    albums: albums
    comments: comments
    posts: posts

    